syntax = "proto3";

package game;

message Vec3f {
    float x = 1;
    float y = 2;
    float z = 3;
}

message Vec3i {
    sint32 x = 1;
    sint32 y = 2;
    sint32 z = 3;
}

message PropertyData {
    string type = 1;
    string value = 2;
}

message PaletteData {
    map<string, PropertyData> attributes = 1;
    int32 materialIndex = 2;
    int32 hash = 3;
}

message ChunkData {
    repeated PaletteData palette = 1;
    repeated uint32 materialsData = 2 [packed = true];
    repeated float densitiesData = 3;
    Vec3i chunkPosition = 4;
}

message WorldProp {
    Vec3f position = 1;
    Vec3f scale = 2;
    Vec3f rotation = 3;
    string model = 4;
    int32 id = 5;
}

message PropsData {
    Vec3i chunkPosition = 1;
    repeated WorldProp props = 2;
}

message UnloadChunk {
    Vec3i chunkPosition = 1;
}

message LoadChunkRequest {
    Vec3i chunkPosition = 1;
}


message PlayerMoveData {
    Vec3f position = 1;
    string name = 2;
}

message PlayerJoin {
    string name = 1;
}

message PlayerLeave {
    string name = 1;
}

message ItemStack {
    string name = 1;
    int32 count = 2;
    map<string, PropertyData> attributes = 3;
}

message InventorySync {
    repeated ItemStack items = 1;
    ItemStack holding = 2;
}

message InventoryUpdate {
    int32 slot = 1;
}

message HotbarSelectUpdate {
    int32 slot = 1;
}

message HoldingItemUpdate {
    string itemName = 1;
    string playerName = 2;
}

message ItemUseAttack {
    
}