export enum PacketTypes {
    PLAYER_JOIN_PACKET = 0,
    PLAYER_MOVE_PACKET = 1,
    CHUNK_DATA_PACKET = 2,
    CHUNK_LOAD_REQUEST_PACKET = 3,
    PLAYER_LEAVE_PACKET = 4,
    INVENTORY_UPDATE = 5,
    INVENTORY_SYNC = 6,
    HOTBAR_SELECT_UPDATE = 7,
    HOLDING_ITEM_UPDATE = 8,
}