
export enum EventType {
    // Common
    SEND_PACKET,
    SEND_PACKET_TO_PLAYER,
    SEND_PACKET_TO_CONNECTION,
    FATAL_CRASH_STATE,

    // Client
    CLIENT_SOCKET_CONNECTED,
    CLIENT_PLAYER_JOINED,
    CLIENT_PLAYER_MOVED,
    CLIENT_ADD_TO_SCENE,
    CLIENT_REMOVE_FROM_SCENE,
    CLIENT_CHUNK_RECEIVED, // TODO: Implement
    CLIENT_PROPS_RECEIVED,
    CLIENT_TOGGLE_POINTER_LOCK,
    CLIENT_INVENTORY_SLOT_CLICKED,
    CLIENT_INVENTORY_SYNC,
    CLIENT_HOTBAR_SELECTION_CHANGED,
    CLIENT_HANDHELD_ITEM_UPDATE,
    CLIENT_MULTIPLAYER_PLAYER_HANDHELD_UPDATE,
    CLIENT_ATTACK,
    CLIENT_UNLOAD_CHUNK,
    
    // Server
    SERVER_PLAYER_JOINED,
    SERVER_PLAYER_LEFT,
    SERVER_PLAYER_LEFT_WS,
    SERVER_PLAYER_MOVED,
    SERVER_LOAD_CHUNK,
    SERVER_INVENTORY_UPDATE,
    SERVER_PLAYER_HOTBAR_SELECT_UPDATE,
    SERVER_USE_ATTACK,
    SERVER_GET_PLAYERS
    
    
}